name: OWASP ZAP Baseline Scan

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start app (exemple Node)
        run: |
          npm install --legacy-peer-deps
          nohup npm run start &  # ou autre commande pour démarrer l'app
          sleep 15

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "http://localhost:4200"
